name: Pull request

on: [pull_request]

jobs:
  Build:
    name: Build & Test
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        api: [ 28 ]
        abi: [ x86 ]
        tag: [ 'default']
#        include:
#          - api: 31
#            abi: x86_64
#            tag: 'google_apis'
#          - api: 30
#            abi: x86
#            tag: 'google_apis'
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Debug keystore
        run: keytool -genkey -v -keystore app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
      - name: Build GedcomGraph
        run:
          cd GedcomGraph && mvn install
      - name: Build
        run: ./gradlew clean assemble
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
      - name: Run tests
        run: ./gradlew test
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Android Emulator test
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew cAT
          api: ${{ matrix.api }}
          tag: ${{ matrix.tag }}
          abi: ${{ matrix.abi }}
          cmdOptions: -noaudio -no-boot-anim -no-window
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
      - uses: actions/upload-artifact@v3.1.1
        if: ${{ always() }}
        with:
          name: GEM-Espresso-${{ matrix.api }}-${{ matrix.abi }}-report
          path: ./**/build/reports/androidTests/connected
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: GEM-Screenshots-${{ matrix.api }}-${{ matrix.abi }}
          path: |
            app/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            app/build/outputs/androidTest-results/connected
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          submodules: 'recursive'
      - name: Build GedcomGraph
        run:
          cd GedcomGraph && mvn install
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v3.1.1
        if: ${{ always() }}
        with:
          name: GEM-Lint-report
          path: ./**/build/reports/lint-results.html
